/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AppState {
  key: string;
  updatedAt: string;
  value: string | null;
}

export interface Client {
  archived: Generated<number>;
  createdAt: Generated<string>;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<string>;
}

export interface NotificationEvent {
  createdAt: Generated<string>;
  id: Generated<number>;
  notificationSentAt: string | null;
  notificationType: string | null;
  sessionId: number;
  thresholdMinutes: number;
  thresholdReachedAt: string;
}

export interface PauseEvent {
  createdAt: Generated<string>;
  id: Generated<number>;
  pausedAt: string;
  reason: string | null;
  resumedAt: string | null;
  sessionId: number;
}

export interface Project {
  archived: Generated<number>;
  clientId: number | null;
  color: string | null;
  createdAt: Generated<string>;
  description: string | null;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<string>;
}

export interface Session {
  createdAt: Generated<string>;
  endedAt: string | null;
  id: Generated<number>;
  note: string | null;
  projectId: number | null;
  startedAt: string;
  status: "active" | "paused" | "completed";
  thresholdMinutes: number | null;
}

export interface SessionTag {
  createdAt: Generated<string>;
  sessionId: number;
  tagId: number;
}

export interface Tag {
  createdAt: Generated<string>;
  id: Generated<number>;
  name: string;
}

export interface DB {
  appState: AppState;
  clients: Client;
  notificationEvents: NotificationEvent;
  pauseEvents: PauseEvent;
  projects: Project;
  sessions: Session;
  sessionTags: SessionTag;
  tags: Tag;
}
