/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface EntryTags {
  created_at: Generated<string>;
  tag_id: number;
  time_entry_id: number;
}

export interface Projects {
  archived: Generated<number>;
  color: string | null;
  created_at: Generated<string>;
  description: string | null;
  id: Generated<number>;
  name: string;
  updated_at: Generated<string>;
}

export interface Tags {
  created_at: Generated<string>;
  id: Generated<number>;
  name: string;
}

export interface TimeEntries {
  created_at: Generated<string>;
  description: string;
  ended_at: string | null;
  id: Generated<number>;
  project_id: number | null;
  started_at: string;
}

export interface DB {
  entry_tags: EntryTags;
  projects: Projects;
  tags: Tags;
  time_entries: TimeEntries;
}
